### ISSUE TITLE
Unable to make runnable jar - Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentialsProvider

### ISSUE THREAD

**Issue by NateZ7** [cloudyr/aws.s3#195]
I have a code to download a file from S3 using java.
I'm able to do that using the Intellij.
I want to create a runnable Jar and run it whenever.

I create the following task -

```
task testJar(type: Jar) {
    from sourceSets.main.runtimeClasspath
    manifest {
        attributes 'Description': 'This is an application JAR',
         'Main-Class': 'com.appname.AWSUpdater'
    }
}
```

I get an output of a Jar including all the AWS Jars, the manifest and my class inside.
When I try to do `java -jar name of jar` I'm getting the following error -

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentialsProvider
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentialsProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

any idea ? thanks !

**Comment by leeper** [comment]
No idea. This is the wrong place to ask - this package doesn't use Java. Try asking on StackOverflow or ask AWS directly for help.
